name: tree_traversal
description: tree_traversal
version: 0.1.0
repository: https://github.com/mcmah309/tree_traversal

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
